name: 'Cache node-modules'
description: 'Cache node-modules'
inputs:
  hashFiles:
    type: string
    required: false
    default: 'yarn.lock'
    description: 'A File to create cache hash'

runs:
  using: "composite"
  steps:
    - name: 'Cache'
      uses: actions/cache@v3
      with:
        path: node_modules
        key: nodemodules-${{ hashFiles(inputs.hashFiles) }}
        restore-keys: nodemodules-