name: 'Prepare Node Version'
description: 'Prepare and install Node from either node-version file or input'
inputs:
  nodeVersion:
    type: string
    description: 'Node version to use'
    required: false
    default: ''
  nodeVersionFile:
    type: string
    description: 'Node version file to use'
    required: false
    default: '.node-version'

runs:
  using: "composite"
  steps:
    - name: 'Check node-version file exists'
      shell: bash
      id: check-node-version-file
      continue-on-error: true
      run: |
        [ -f ${{ inputs.nodeVersionFile }} ] && { exit 0; exit 1; }
    - name: 'Setup Node from node-version file'
      if: steps.check-node-version-file.outcome == 'success'
      uses: actions/setup-node@v3
      with:
        node-version-file: ${{ inputs.nodeVersionFile }}
    - name: 'Setup Node from input'
      if: steps.check-node-version-file.outcome != 'success'
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.nodeVersion }}