name: 'Run tests & check coverage workflow'
on:
  workflow_call:
    inputs:
      runAfterInstall:
        type: string
        required: false
        description: Commands to run after installing dependencies.

jobs:
  run-tests-check-coverage:
    runs-on: ubuntu-20.04
    name: Run tests & check coverage
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodemodules-${{ hashFiles('yarn.lock') }}
          restore-keys: nodemodules-

      - name: Install Node packages
        run: yarn install

      - name: 'Run after install commands'
        run: ${{ inputs.runAfterInstall }}
        if: ${{ inputs.runAfterInstall != '' }}

      - name: Build
        run: yarn build

      - name: Run tests and prepare coverage report
        run: yarn test:coverage

      - name: Read coverage text report
        uses: fingerprintjs/action-coverage-report-md@v1
        id: coverage-md

      - name: Jest coverage comment
        id: coverage
        uses: ArtiomTr/jest-coverage-report-action@df2b025553c31d68f84be6337843e277e2576844
        with:
          package-manager: yarn
          output: report-markdown

      - name: Add comment with coverage report
        uses: marocchino/sticky-pull-request-comment@adca94abcaf73c10466a71cc83ae561fd66d1a56
        with:
          message: |
            ${{ steps.coverage.outputs.report }}
            <details>
              <summary>Show full coverage report</summary>

              ${{ steps.coverage-md.outputs.markdownReport }}
            </details>
