name: 'Generate docs and coverage report'
on:
  workflow_call:
    inputs:
      run-after-install:
        type: string
        required: false
        description: Commands to run after installing dependencies.
      prepare-gh-pages-commands:
        required: false
        default: |
          mv docs ./gh-pages
          mv coverage/lcov-report ./gh-pages/coverage
        type: string
        description: >
          Commands to prepare the content of the gh-pages folder. The gh-pages folder will be created automatically.
          Only specify the commands for moving files into it.
      skip-docs-step:
        required: false
        default: false
        type: boolean
        description: "Skip the documentation generation step."

jobs:
  generate-docs-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: nodemodules-${{ hashFiles('yarn.lock') }}
          restore-keys: nodemodules-

      - name: Install dependencies
        run: yarn install

      - name: Run after install
        run: ${{ inputs.run-after-install }}
        if: ${{ inputs.run-after-install != '' }}

      - name: Build
        run: yarn build

      - name: Create the docs
        if: ${{ inputs.skip-docs-step != 'true' }}
        run: yarn docs

      - name: Collect coverage report
        run: yarn test:coverage

      - name: Create Coverage Badges
        uses: jaywcjlove/coverage-badges-cli@e07f25709cd25486855c1ba1b26da53576ff3620
        with:
          source: coverage/coverage-summary.json
          output: coverage/lcov-report/badges.svg

      - name: Prepare folder for gh-pages
        run: |
          mkdir gh-pages
          ${{ inputs.prepare-gh-pages-commands }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@8817a56e5bfec6e2b08345c81f4d422db53a2cdc
        with:
          branch: gh-pages
          folder: gh-pages
