name: 'Release TypeScript project'
on:
  workflow_call:
    inputs:
      runAfterInstall:
        type: string
        required: false
        description: Commands to run after installing dependencies.
    secrets:
      GH_RELEASE_TOKEN:
        required: true
      NPM_AUTH_TOKEN:
        required: true

jobs:
  build-and-check:
    name: 'Build project and run CI checks'
    uses: ./.github/workflows/build-typescript-project.yml
    with:
      runAfterInstall: ${{ inputs.runAfterInstall }}

  release:
    name: 'Release'
    needs: build-and-check
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: 'Cache'
        uses: actions/cache@v3
        with:
          path: node_modules
          key: nodemodules-${{ hashFiles('yarn.lock') }}
          restore-keys: nodemodules-

      - name: 'Install Dependencies and prepare packages'
        run: yarn install
        env:
          CI: true

      - name: 'Run after install commands'
        run: ${{ inputs.runAfterInstall }}
        if: ${{ inputs.runAfterInstall != '' }}

      - name: 'Semantic Release'
        uses: cycjimmy/semantic-release-action@91ab76a4a393a8d0c4739e9aea1818b56bc953ea
        with:
          extra_plugins: |
            @semantic-release/exec@6.0.3
            conventional-changelog-conventionalcommits@5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          HUSKY: 0

