name: 'Test reusable workflows'
on:
  push:

jobs:
  release-server-sdk-python:
    name: 'Build project and run CI checks'
    uses: ./.github/workflows/release-server-sdk.yml
    with:
      language: python
      language-version: '3.9'
      prepare-command: 'echo "prepare python"'
    secrets:
      GH_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
