name: 'Test reusable workflows'
on:
  pull_request:

jobs:
  release-server-sdk-python:
    name: 'Release Python SDK'
    uses: ./.github/workflows/release-server-sdk.yml
    with:
      language: python
      language-version: '3.9'
      prepare-command: 'echo "prepare python"'
    secrets:
      GH_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release-server-sdk-dotnet:
    name: 'Release DotNET SDK'
    uses: ./.github/workflows/release-server-sdk.yml
    with:
      language: dotnet
      language-version: '7.x'
      prepare-command: 'echo "prepare DotNET"'
    secrets:
      GH_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release-server-sdk-php:
    name: 'Release PHP SDK'
    uses: ./.github/workflows/release-server-sdk.yml
    with:
      language: php
      language-version: '7.3'
      prepare-command: 'echo "prepare PHP"'
    secrets:
      GH_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release-server-sdk-golang:
    name: 'Release Go SDK'
    uses: ./.github/workflows/release-server-sdk.yml
    with:
      language: golang
      language-version: '1.19'
      prepare-command: 'echo "prepare golang"'
    secrets:
      GH_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  success-job:
    runs-on: ubuntu-latest
    steps:
      - name: This step always succeeds
        run: echo "Success!"

  failed-job:
    runs-on: ubuntu-latest
    steps:
      - name: This step always fails
        run: exit 1

  notify-success:
    needs: success-job
    if: always()
    uses: ./.github/workflows/report-workflow-status.yml
    with:
      notification_title: 'DX tools: test workflow-status-reporter success scenario'
      job_status: ${{ needs.success-job.result }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  notify-fail:
    needs: failed-job
    if: always()
    uses: ./.github/workflows/report-workflow-status.yml
    with:
      notification_title: 'DX tools: test workflow-status-reporter fail scenario'
      job_status: ${{ needs.failed-job.result }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
